numbers=[50,40,23,70,56,12,5,10,7]
i=1
count=0
while i<len(numbers):
    count=count+1
    i=i+1 
print(i)       





    

    


    



    
      











 


























                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          