mixed_list=["rahul",12,9.0,"kaavay","shivam",1]
i=1
b=[]
while i<=len(mixed_list):
    b.append(mixed_list[-i])
    i=i+1
print(b)
                                                                                                                                                                                                                                                                                                            